name: flipper_notification
description: "A new Flutter plugin project."
version: 0.0.1
# homepage:

environment:
  sdk: ">=3.3.1 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  ffi: ^2.1.2
  flutter:
    sdk: flutter
  flutter_rust_bridge: ^1.82.6
  freezed_annotation: ^2.4.1
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  ffigen: ^8.0.0
  build_runner: ^2.4.8
  freezed: ^2.4.7

flutter:
  plugin:
    platforms:
      windows:
        pluginClass: FlipperNotificationPluginCApi
